### ISSUE TITLE
Questions about random affine augmentation

### ISSUE THREAD

**Issue by bryanyzhu** [simonmeister/UnFlow#13]
Hi Simon, I got another question about the random affine augmentation during training. The code snippet is [here](https://github.com/simonmeister/UnFlow/blob/master/src/e2eflow/core/unsupervised.py#L40-L51). I don't understand why there is a local augmentation on the im2_geo again. Is it because we want more distortions? I saw similar operation in Jason's UnsupFlowNet caffe implementation before. I didn't figure out either. So could you give me some help here? Thank you.

**Comment by simonmeister** [comment]
The two images are first geometrically distorted together as a standard way of reducing overfitting. However, we can also generate a larger variation in flow fields seen during training by applying a additional spatial transform to the second image, so that we see a larger range of displacements between images during training (the spatial transform can be seen as just another example of ïmage motion). I think this is described first in the original FlowNet paper.

**Comment by bryanyzhu** [comment]
Thanks a lot, I see it now.
