### ISSUE TITLE
Check failed: dim.IsSet() Internal error: Got nullptr for Dimension in downsample

### ISSUE THREAD

**Issue by lenazherdeva** [simonmeister/UnFlow#34]
Hello, thanks again for your work!

I have a question. In `unsupervised.py` I have `im1_s, im2_s` with shapes `(2, 320, 1152, ?)`. After first `downsample(im1_s, 4)` shapes became `(2, 80, 288, ?)`, and then in each iteration when computing loss (https://github.com/simonmeister/UnFlow/blob/master/src/e2eflow/core/unsupervised.py#L116)

 I have `downsample(im1_s, 2)` and shapes decreasing twice. So, once, I have shape `(2, 5, 18, ?)`, and there is an error:

> /usr/local/lib/python3.5/dist-packages/tensorflow/include/tensorflow/core/framework/shape_inference.h:625] Check failed: dim.IsSet() Internal error: Got nullptr for Dimension
.
Aborted (core dumped)

What can cause such a problem and how can I solve it?

**Comment by simonmeister** [comment]
I'm not sure. It could be that it doesn't know the channel dimension and you may need to make sure that it is known (e.g. by doing a explicit reshape somewhere at the end of the input stage).

**Comment by lenazherdeva** [comment]
It didn't help, maybe it's because of odd dimension of input and I'm trying to downsample it by 2?

**Comment by simonmeister** [comment]
Yes, if you input odd dimensions into downsample it won't work - in that case you need to re-scale (e.g. bilinearly) before.

**Comment by yangengt123** [comment]
Hi lenazherdeva , 

Did you find any additional cues or solution for this error.

 I use the default config.ini setting, using synthia dataset with image size (448, 640), and get the same error in the third time downsample, the time it tries to downsample the 'border_mask'  (Line 147 in unsupervised.py). 

Do you meet this error in the same setting? Could you help me for this? 

Thanks!

Update: The size stated in config.ini currently (448, 640) is different from the size stated in paper. By change the number back to (512, 768), the problem is solved.

**Comment by lenazherdeva** [comment]
Hi, yangengt123!

It's nice!

But if you will use other sizes: I just check that in the last iteration of downsampling that it's odd size and I don't do downsampling. (It's for kitti dataset for example).
